### ISSUE TITLE
タイポ

### ISSUE THREAD

**Issue by k-jun** [kujirahand/book-mlearn-gyomu#1]
書籍pythonによるAI・機械学習・深層学習の作り方
p. 305サンプルコード
for j, f in enumerate(fs):
		img = cv2.imread(f)
		img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
		img = cv2.resize(img_gray, (im_size, im_size))
		result.append([i, img])
		if j == 3:
			plt.subplot(11, 5, i+1)
			plt.axis("off")
			plt.title(str(i))
			plt.imshow(img, cmap='gray')

img = cv2.resize(img, (im_size, im_size)) => img = cv2.resize(img_gray, (im_size, im_size))
だと思われます。

**Comment by kujirahand** [comment]
068b88b8a330c7f2bd918769779211189e223781 で修正しました。
ご報告に感謝です！
