### ISSUE TITLE
ch5/recog/CNN.ipynbを開くことができない

### ISSUE THREAD

**Issue by renkarsu** [kujirahand/book-mlearn-gyomu#11]
kujirahand様

　renkarsuと申します．

　タイトルの通り，ch5/recog内のCNN.ipynbがGoogle Colabで開けません．
　GithubのRawタブをクリックして中身を見てみましたが，自分には要修正箇所が分かりませんでしたので，報告のみとさせていただきます．

　一般的なissueと比べて多少硬い文体で書いていますが，お気軽にコメントをいただけると幸いです．

以上です．よろしくお願いいたします．

**Comment by kujirahand** [comment]
書き込みありがとうございます。
GoogleのColabだとバージョン依存で動かないことも多く、Colabでは最初の方のかんたんなサンプルを動かすことを念頭においています。
そこで、5章ではPCにJupyter Notebookをインストールして、利用することをおすすめします。

**Comment by renkarsu** [comment]
ご回答ありがとうございます．
インポートエラーではなく，ファイルを開くことができないのですが，Colabのバージョンによって，そのようなエラーが出ることは初めて知りました．勉強になりました．ありがとうございます．
