### ISSUE TITLE
ファイルオープンエラー

### ISSUE THREAD

**Issue by lifeisegg2k** [kujirahand/book-mlearn-gyomu#12]
お疲れ様です。

[CNN.ipynb](https://github.com/kujirahand/book-mlearn-gyomu/blob/master/src/ch5/recog/CNN.ipynb)を開くのができません。

ご確認願います。

**Comment by kujirahand** [comment]
お返事が遅れしまい申し訳ありませんでした。以下、修正しました。
https://github.com/kujirahand/book-mlearn-gyomu/blob/master/src/ch5/recog/CNN.ipynb
