### ISSUE TITLE
Ch5のコード

### ISSUE THREAD

**Issue by toshifumikuroda** [kujirahand/book-mlearn-gyomu#13]
2020年出版のTensorFlow2対応版のCh5.2で扱われているじゃんけんのコードが含まれていないようです。

**Comment by kujirahand** [comment]
ジャンケンのコード、以下にありますので、参考にしてください。
https://github.com/kujirahand/book-mlearn-gyomu/tree/master/src/ch5/janken

**Comment by toshifumikuroda** [comment]
旧版のファイルをダウンロードしていました。ご対応頂きありがとうございました。
